<?php
return[
  "customer_id_Carrier" => "Заказчика (Перевозчик)",
  "application_title_Carrier" => "Заголовок заявки (Перевозчик)",
    "date_Carrier" => "Дату",
    "carrier_id_Carrier" => "Перевозчика",
    "customer_id_Client" => "Заказчика (Клиент)",
    "application_title_Client" => "Заголовок заявки (Клиент)",
    "proxy_Client" => "Номер договоренности",
    "client_id_Client" => "Клиента",
    "driver_id_Carrier" => "Водителя (Перевозчик)",
    "driver_id_Client" => "Водитель (Клиент)",
    "car_brand_id_Carrier" => "Марку (Перевозчик)",
    "government_number_Carrier" => "Гос. номер (Перевозчик)",
    "semitrailer_Carrier" => "П/П (Перевозчик)",
    "type_transport_id_Carrier" => "Тип транспорта (Перевозчик)",
    "type_carcase_id_Carrier" => "Тип кузова (Перевозчик)",
    "type_carcase_id_Client" => "Тип кузова (Клиент)",
    "car_brand_id_Client" => "Макру (Клиент)",
    "government_number_Client" => "Гос.номер (Клиент)",
    "semitrailer_Client" => "П/П (Клиент)",
    "type_transport_id_Client" => "Тип транспорта (Клиент)",
    "nature_cargo_Carrier" => "Характер груза (Перевозчик)",
    "place_Carrier" => "Место (Перевозчик)",
    "weight_Carrier" => "Вес (Перевозчик)",
    "ref_mode_Carrier" => "Реф.режим (Перевозчик)",
    "nature_cargo_Client" => "Характер груза (Клиент)",
    "place_Client" => "Место (Клиент)",
    "weight_Client" => "Вес (Клиент)",
    "ref_mode_Client" => "Реф.режим (Клиент)",
    "special_conditions_Carrier"  => "Особые условия (Перевозчик)",
    "special_conditions_Client" => "Особые условия (Клиент)",
    "terms_payment_Carrier" => "Условия оплаты (Перевозчик)",
    "transportation_cost_Carrier" => "Стоимость перевозки (Перевозчик)",
    "taxation_type_Carrier" => "Тип налогооблажения (Перевозчик)",
    "terms_payment_Client" => "Условия оплаты (Клиент)",
    "transportation_cost_Client" => "Стоимость перевозки (Клиент)",
    "cost_cargo_Client" => "Стоимость груза (Клиент)",
    "taxation_type_Client" => "Тип налогооблажения (Клиент)",
    "prerequisites_Carrier" => "Обязательные условия",
    "addition" => "Приложение",
    "transportation" => "Транспортировку",
    "fines" => "Штрафы",
    "additional_expenses" => "Доп. рассходы",
    "application_status" => "Статус заявки",


    "application_document_1_type" => "Подписанная заявка от перевозчика (м) (обязательное)",
    "application_document_2_type" => "ТТН/ТН/ЭР (м) * (обязательное)",
    "application_document_3_type" => "Внутренние документы по поездке (м)",
    "application_document_4_type" => "Счет от перевозчика (м) (обязательное)",
    "application_document_5_type" => "Акт/УПД от перевозчика (м) (обязательное)",
    "application_document_6_type" => "Квиток об отправке оригиналов (м) (обязательное)",
    "application_document_7_type" => "Отметка о получении оригиналов от перевозчика (б) ** (обязательное)",
    "application_document_8_type" => "Платежка для перевозчика (б) (обязательное)",
    "application_document_9_type" => "Прочие документы",
    "application_document_10_type" => "Подписанная заявка от клиента (м) (обязательное)",
    "application_document_11_type" => "Доверенность",
    "application_document_12_type" => "Страховка груза (м) (обязательно)",
    "application_document_13_type" => "Счета для клиента (б) (обязательное)",
    "application_document_14_type" => "АКТ/УПД для клиента (б) (обязательное)",
    "application_document_15_type" => "Отметка об отправке оригиналов (счет, ТТН, АКТ/УПД) клиенту (б) (обязательное)",
    "application_document_16_type" => "Отметка об оплате счета (б) (обязательное)",
    "application_document_17_type" => "Прочие документы",

];